### ISSUE TITLE
selection property not binding within another component?

### ISSUE THREAD

**Issue by wasabigeek** [RSSchermer/ember-multiselect-checkboxes#38] opened 2016-10-27 18:35 UTC
I'm using the checkboxes within another component, and can't seem to get the "selection" property working:
`{{multiselect-checkboxes options=platforms selection=selectedPlatforms labelProperty='name' valueProperty='id'}}`

The `selectedPlatforms` property is nowhere to be seen in Ember Inspector, not in the parent component, the checkboxes, or the controller.

**Comment by RSSchermer** [comment] 2016-10-27 20:12
It's somewhat difficult for me to tell what might be going wrong from just that line of code. Because your setting the `valueProperty`, your `selectedPlatforms` should be a collection of ids rather than platform objects. Off hand that's the only thing that I can think of that might be going wrong here. If that isn't it, then a sort of minimal example demonstrating the problem would really help.

**Comment by wasabigeek** [comment] 2016-10-28 06:34
Upon further investigation, if I leave out `valueProperty`, the selection seems to work. Once I include it, it doesn't. Hope this helps:

```
// app/models/survey-option.js
...
export default Model.extend({
  question: DS.attr('string'),
  name: DS.attr('string')
});

// app/templates/survey.hbs
{{ survey-form options=model }}

// app/routes/survey.js
...
export default Ember.Route.extend({
  model() {
    return this.store.findAll('survey-option');
  }
});

// app/components/survey-form.js
...
export default Ember.Component.extend({
  platforms: Ember.computed.filterBy('options', 'question', 'platform'),
  selectedPlatforms: Ember.A(),
});

// app/templates/components/survey-form.hbs
...
{{multiselect-checkboxes options=platforms selection=selectedPlatforms labelProperty='name' valueProperty='id'}} // I tried using valueProperty='name' as well, didn't work
...
```

**Comment by RSSchermer** [comment] 2016-10-28 09:24
Thanks!

I think then that the problem stems from a misunderstanding of what the `valueProperty` attribute does. The `valueProperty` attribute was intended for cases where you don't want your selection to be a collection of entire option objects, but rather a collection of for example their IDs. See #8 for the original use case. The `valueProperty` attribute does not control how the checkboxes are displayed, it only tells the `multiselect-checkboxes` component how to update the collection bound the the `selection` attribute.

In this case you do seem to in fact be binding a collection of complete option objects to the `selection` attribute, not a collection of only their IDs. In that case you probably don't want to use the `valueProperty` attribute. If you do want the `selection` to be a collection of IDs, rather than option objects, then you should first first map them to their IDs:

```js
// app/components/survey-form.js
...
export default Ember.Component.extend({
  platforms: Ember.computed.filterBy('options', 'question', 'platform').mapBy('id'),
  selectedPlatforms: Ember.A(),
});
```

Does that help?

**Comment by RSSchermer** [comment] 2016-11-08 21:11
Closing for now. Feel free to reopen if this issue persists.

**Closed by RSSchermer** 2016-11-08 21:11 UTC
